Update the changelog for version 20.6.1
EventStore/EventStore pull request #2705
Opened 2020-10-01 12:46 UTC by hayley-jean

2020-10-01 17:21 UTC, bartelink commented on CHANGELOG.md
> +- Prevent clients from connecting to read only replicas which have not yet caught up [EventStore#2674](https://github.com/EventStore/EventStore/pull/2674)
```suggestion
- Prevent clients from connecting to read only replicas which have not yet caught up [EventStore#2674](https://github.com/EventStore/EventStore/pull/2674) :pray: @01100010011001010110010101110000 
```

2020-10-02 08:13 UTC, mat-mcloughlin submitted a review, later dismissed

2020-10-05 09:19 UTC, thefringeninja approved these changes

2020-10-05 09:20 UTC, thefringeninja requested changes
What's up with the :pray: icon

2020-10-05 09:41 UTC, bartelink commented
it conveys "thanks to the external contributor" @githubhandle  😉

2020-10-05 10:11 UTC, hayley-jean commented
@thefringeninja I've changed the emoji to just a `Thanks to` to make it a bit clearer

2020-10-06 08:54 UTC, thefringeninja commented
@bartelink TIL!

2020-10-06 08:55 UTC, thefringeninja submitted a review, later dismissed

2020-10-08 09:01 UTC, shaan1337 reviewed
This line should be removed since we replaced the --disable-https flag with --insecure:
https://github.com/EventStore/EventStore/pull/2705/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR53

2020-10-08 12:14 UTC, thefringeninja approved these changes

2020-10-08 12:39 UTC, alexeyzimarev commented on CHANGELOG.md
>  - requests with more than one url segment are correctly routed [EventStore#2691](https://github.com/EventStore/EventStore/pull/2691)
Shall we fix all capitalisation issues from the previous update?

2020-10-09 12:15 UTC, alexeyzimarev approved these changes

2020-10-09 13:39 UTC, thefringeninja approved these changes

2020-10-09 13:39 UTC, merged