Fix performance counter error message on linux / macOS
EventStore/EventStore pull request #2775
Opened 2021-01-07 07:04 UTC by shaan1337

Fixed: Performance counter error message on linux / macOS

Fixes: https://github.com/EventStore/home/issues/332

Create CPU & memory performance counters on Windows only since on Linux & macOS use the [HostStat.NET](https://www.nuget.org/packages/HostStat.NET/) library

2021-01-07 11:34 UTC, jageall requested changes

2021-01-07 11:34 UTC, jageall commented on src/EventStore.Core/Services/Monitoring/Utils/PerfCounterHelper.cs
> +			_totalMemCounter = Runtime.IsWindows ? CreatePerfCounter("Memory", "Available Bytes") : null;
If we move this check inside CreatePerfCounter then we only need to add a guard clause at the beginning (outside the try block) and if any subsequent counters ever get added, we won't forget that the perfcounters only exist on windows

2021-01-11 08:41 UTC, thefringeninja approved these changes

2021-01-11 09:29 UTC, arwinneil approved these changes

2021-01-11 10:04 UTC, merged