Use checkpointInterval Intead of CheckpointIntervalMultiplier in Filtered Subscriptions
EventStore/EventStore pull request #2795
Opened 2021-01-21 10:56 UTC by thefringeninja

2021-01-21 11:33 UTC, jageall requested changes

2021-01-21 11:33 UTC, jageall commented on src/EventStore.Core/Services/Transport/Grpc/Enumerators.AllSubscriptionFiltered.cs
> -					string.Empty, _resolveLinks, _user, _eventFilter, (int)_checkpointIntervalMultiplier));
_checkpointIntervalMultiplier doesn't appear to be used outside the constructor for calculating the checkpointInterval. maybe we can remove it?

2021-01-27 09:05 UTC, YoEight approved these changes

2021-01-27 12:36 UTC, hayley-jean approved these changes

2021-01-29 08:18 UTC, YoEight approved these changes

2021-01-29 08:56 UTC, hayley-jean approved these changes

2021-01-29 08:57 UTC, merged