Changes GossipOnSingleNode to be on by default
EventStore/EventStore pull request #2818
Opened 2021-02-12 14:31 UTC by jageall

Changed: GossipOnSingleNode is now on by default and the setting has been deprecated in config

2021-02-13 19:46 UTC, thefringeninja submitted a review, later dismissed

2021-02-15 08:26 UTC, hayley-jean requested changes
We also need to disable `DiscoverViaDns` on a single node, otherwise Event Store constantly tries to resolve a non-existent dns and logs out: 

```
[27056,12,09:24:45.410,ERR] Error while retrieving cluster members through DNS.
System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at EventStore.Core.Services.Gossip.DnsGossipSeedSource.EndGetHostEndpoints(IAsyncResult asyncResult) in C:\Users\hayle\code\EventStore\src\EventStore.Core\Services\Gossip\DnsGossipSeedSource.cs:line 20
   at EventStore.Core.Services.Gossip.GossipServiceBase.OnGotGossipSeedSources(IAsyncResult ar) in C:\Users\hayle\code\EventStore\src\EventStore.Core\Services\Gossip\GossipServiceBase.cs:line 102
[27056,24,09:24:46.269,INF] Exiting with exit code: 0.
```

2021-02-15 10:07 UTC, hayley-jean approved these changes

2021-02-15 10:51 UTC, thefringeninja approved these changes

2021-02-15 10:52 UTC, merged