Configuration Changes
EventStore/EventStore pull request #2833
Opened 2021-03-02 19:54 UTC by thefringeninja

2021-03-19 10:36 UTC, hayley-jean requested changes
The new format looks good!

A few issues that have come up in testing so far:
- Command line arguments don't override options set in the config file
- `RunProjections: All` or `RunProjections: System` doesn't start the projections subsystem
- Environment variables don't seem to affect the options (only tested on Windows though)

I've also suggested a few changes to copy over the deprecated messages we currently have on master

2021-03-19 10:36 UTC, hayley-jean commented on src/EventStore.Core/ClusterVNodeOptions.cs
> +			[Description("Enable AtomPub over HTTP Interface.")]
```suggestion
			[Description("Enable AtomPub over HTTP Interface."),
			Deprecated("AtomPub over HTTP Interface has been deprecated as of version 20.6.0. It is recommended to use gRPC instead")]
```

2021-03-19 10:36 UTC, hayley-jean commented on src/EventStore.Core/ClusterVNodeOptions.cs
> +			[Description("Whether to enable external TCP communication")]
```suggestion
			[Description("Whether to enable external TCP communication"),
			Deprecated("The Legacy TCP Client Interface has been deprecated as of version 20.6.0. It is recommended to use gRPC instead.")]
```

2021-03-26 10:19 UTC, hayley-jean requested changes
Thanks! The order of precedence, environment variables and subsystems work for me now.

Two additional issues found in testing:

1. If I try to start the server with an auth plugin using a config section rather than a separate file, I get an error saying the option doesn't exist:

```
Error while parsing options: The option LdapsAuth is not a known option. (Parameter 'LdapsAuth')
```

2. The TestClient doesn't print its effective options on startup. `--what-if` also doesn't work.

2021-03-26 16:45 UTC, thefringeninja commented on src/EventStore.ClusterNode/Program.cs
> +					// ReSharper disable MethodSupportszzzzzzzzzCancellation
Must have fallen asleep on my keyboard 🙄

2021-04-07 12:13 UTC, hayley-jean approved these changes

2021-04-09 09:20 UTC, arwinneil approved these changes

2021-04-09 09:22 UTC, merged