Use an interpreter for user projections
EventStore/EventStore pull request #2951
Opened 2021-05-12 08:07 UTC by jageall

Added: Interpreter runtime for user projections
Added: Options to switch user runtime back to legacy v8
Changed: Change the user projection runtime to use an interpreter rather than v8

Fixes: #2946 , home#500
Notes:
The option to switch runtimes is marked as deprecated so that if legacy is selected it will print the deprecation warning

2021-05-19 13:54 UTC, hayley-jean requested changes
I've added a spec that fails due to the body of the event being different to the legacy runtime

We should also look at adding checks similar to the ones in https://github.com/EventStore/EventStore/pull/2947 to filter out scavenged events

2021-05-26 08:34 UTC, jageall commented
> I've added a spec that fails due to the body of the event being different to the legacy runtime

Fixed

2021-05-27 11:52 UTC, YoEight approved these changes

2021-06-02 07:03 UTC, thefringeninja requested changes

2021-06-02 07:03 UTC, thefringeninja commented on src/EventStore.Projections.Core.Tests/Services/Jint/when_running_emitting_js_projection.cs
> +{
I think the formatting here is wrong

2021-06-04 09:35 UTC, hayley-jean approved these changes

2021-06-04 11:05 UTC, YoEight approved these changes

2021-06-04 11:25 UTC, merged