Updated TryDecodeCredential to split on a maximumof two :
EventStore/EventStore pull request #3070
Opened 2021-07-22 19:36 UTC by StevenBlair123

2021-07-23 11:18 UTC, jageall requested changes

2021-07-23 11:18 UTC, jageall commented on src/EventStore.Core/Services/Transport/Http/Authentication/BasicHttpAuthenticationProvider.cs
> +	using System;
This using should be moved up with the rest of the usings abobe

2021-07-23 11:18 UTC, jageall commented on src/EventStore.Core/Services/Transport/Http/Authentication/BasicHttpAuthenticationProvider.cs
> +			                                                                                                                                    values[0],
nit: formatting

2021-07-26 07:35 UTC, hayley-jean approved these changes
Thanks! Looks good 👍

2021-07-26 08:44 UTC, jageall approved these changes

2021-07-26 09:16 UTC, thefringeninja approved these changes

2021-07-26 09:16 UTC, merged