Allow the server to send a list of supported gRPC methods to clients
EventStore/EventStore pull request #3194
Opened 2021-09-28 10:07 UTC by hayley-jean

Added: FeatureDiscovery proto for discovering which gRPC methods are available on the server

Adds a simple gRPC service that provides a list of all gRPC endpoints available on the server.
The `ApiVersion` is hardcoded to 1 for now.

The supported methods look like the following:

```
```

**Feedback**
- Suggestions for a better name would be appreciated
- Should the supported methods be grouped by service, which then itself could have a version? Or is a flat list better?

2021-09-30 11:56 UTC, thefringeninja requested changes

2021-09-30 11:56 UTC, thefringeninja commented on src/EventStore.Core.Tests/Services/Transport/Grpc/ClientCapabilitiesTests/ClientCapabilitiesTest.cs
> +                _expectedEndPoints.AddRange(GetEndPoints(Client.Monitoring.Monitoring.Descriptor));
formatting

2021-10-01 11:44 UTC, YoEight approved these changes

2021-10-04 14:43 UTC, thefringeninja approved these changes

2021-10-04 14:44 UTC, merged