Make Leader Election timeout configurable
EventStore/EventStore pull request #3263
Opened 2021-11-03 11:14 UTC by hayley-jean

Added: LeaderElectionTimeoutMs option to allow configuring the timeout for election messages.

Backports PR https://github.com/EventStore/EventStore/pull/3121 to 20.10.
Fixes https://github.com/EventStore/home/issues/605.
Adds the `LeaderElectionTimeoutMs` option which configures the LiveUntil and Deadlines of messages in ElectionsService

- Deadlines when sending messages over gRPC will be based on the LiveUntil of the messages, rather than setting a deadline separately.
- Update GossipService to use the GossipTimeout as the LiveUntil of gossip messages.

2021-11-03 14:30 UTC, thefringeninja requested changes
`docker compose up` is complaining
```
 System.ArgumentOutOfRangeException: leaderElectionTimeout should be greater than 1 second. (Parameter 'leaderElectionTimeout')
 ```

2021-11-03 14:30 UTC, thefringeninja commented on src/EventStore.Core/Services/ElectionsService.cs
> +			if (leaderElectionTimeout.Seconds < 1) {
docker-compose up is complaing:
```
eventstore-esdb-node2-1           | [    1, 1,14:25:43.323,FTL] Host terminated unexpectedly.
eventstore-esdb-node2-1           | System.ArgumentOutOfRangeException: leaderElectionTimeout should be greater than 1 second. (Parameter 'leaderElectionTimeout')
eventstore-esdb-node2-1           |    at EventStore.Core.Services.ElectionsService..ctor(IPublisher publisher, MemberInfo memberInfo, Int32 clusterSize, ICheckpoint writerCheckpoint, ICheckpoint chaserCheckpoint, ICheckpoint proposalCheckpoint, IEpochManager epochManager, Func`1 getLastCommitPosition, Int32 nodePriority, ITimeProvider timeProvider, TimeSpan leaderElectionTimeout) in /build/src/EventStore.Core/Services/ElectionsService.cs:line 104
eventstore-esdb-node2-1           |    at EventStore.Core.ClusterVNode..ctor(TFChunkDb db, ClusterVNodeSettings vNodeSettings, IGossipSeedSource gossipSeedSource, InfoControllerBuilder infoControllerBuilder, ISubsystem[] subsystems) in /build/src/EventStore.Core/ClusterVNode.cs:line 756
eventstore-esdb-node2-1           |    at EventStore.Core.VNodeBuilder.Build(IOptions options, IPersistentSubscriptionConsumerStrategyFactory[] consumerStrategies) in /build/src/EventStore.Core/VNodeBuilder.cs:line 1587
eventstore-esdb-node2-1           |    at EventStore.ClusterNode.ClusterVNodeHostedService.Create(ClusterNodeOptions opts) in /build/src/EventStore.ClusterNode/ClusterVNodeHostedService.cs:line 144
eventstore-esdb-node2-1           |    at EventStore.Core.EventStoreHostedService`1..ctor(String[] args) in /build/src/EventStore.Core/EventStoreHostedService.cs:line 44
eventstore-esdb-node2-1           |    at EventStore.ClusterNode.ClusterVNodeHostedService..ctor(String[] args) in /build/src/EventStore.ClusterNode/ClusterVNodeHostedService.cs:line 34
eventstore-esdb-node2-1           |    at EventStore.ClusterNode.Program.Main(String[] args) in /build/src/EventStore.ClusterNode/Program.cs:line 24
```

2021-11-03 14:51 UTC, hayley-jean commented on src/EventStore.Core/Services/ElectionsService.cs
> +			if (leaderElectionTimeout.Seconds < 1) {
Thanks, this should be fixed now

2021-11-03 15:26 UTC, thefringeninja submitted a review, later dismissed

2021-11-08 07:04 UTC, shaan1337 commented on src/EventStore.Core/Services/ElectionsService.cs
> +					$"{nameof(leaderElectionTimeout)} should be greater than 1 second.");
```suggestion
					$"{nameof(leaderElectionTimeout)} should not be less than 1 second.");
```
Just a small precision to the error message

2021-11-08 07:16 UTC, shaan1337 approved these changes
Noticed an issue which isn't directly related to this PR:

Setting --leader-election-timeout-ms to 1 millisecond (I've commented out the >= 1 second check) then making two nodes elect a leader crashes both nodes with the following error:
```
[11102Unhandled exception. , 4,11:09:32.628,FTL] Global Unhandled Exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Grpc.Net.Client.Internal.GrpcCall`2.DeadlineExceededCallback(Object state)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

2021-11-08 12:34 UTC, shaan1337 approved these changes

2021-11-08 18:05 UTC, thefringeninja approved these changes

2021-11-08 18:05 UTC, merged