Cancel pending writes when deposed
EventStore/EventStore pull request #3500
Opened 2022-06-08 15:55 UTC by jageall

Fixed: Pending writes are cancelled when a leader is deposed. 

This is sent back to the client as a WriteTimeout or CommitTimeout which indicates that the client should retry the request with the exact same values.

Fixes #3472

2022-06-09 09:34 UTC, hayley-jean submitted a review, later dismissed

2022-06-10 09:34 UTC, hayley-jean approved these changes
Code looks good, and while I've not reproduced the original issue, I can confirm that the `ReplicationTrackingService` now shuts down when an offline truncation is about to take place

2022-06-10 11:19 UTC, timothycoleman commented on src/EventStore.Core/Services/RequestManager/RequestManagementService.cs
> +			if (_nodeState == VNodeState.Leader && message.State is not VNodeState.Leader or VNodeState.ResigningLeader) {
do we still want the change in this file? the node is just about to go offline for truncation so this might just be extra noise now

2022-06-10 11:20 UTC, timothycoleman requested changes
looks good, just question

2022-06-10 14:54 UTC, timothycoleman approved these changes
:+1:

2022-06-10 17:01 UTC, timothycoleman commented
Able to reproduce the bug and confirmed that this fixes it.

I set up a three node docker cluster, with three writers, each talking to one node. Each writer writes an event and attempts to read it back in a loop. Used https://github.com/worstcase/blockade to partition the network such that the leader and its writer are separated in their own partition (irl this could correspond to an availability zone), and upon repairing the partition the bug was observed.

Had to artificially widen the window of failure by setting long timeouts (30s) and having the cluster storage writer service sleep for 5s after detecting trunction is required, to give the replication path time to reliably execute. in both cases smaller values would probably have sufficed

2022-06-10 17:09 UTC, merged