Update changelog for 22.6.0
EventStore/EventStore pull request #3521
Opened 2022-07-15 10:29 UTC by hayley-jean

2022-07-21 10:32 UTC, jageall requested changes
This will need updating with the recent fixes from this week, but the rest looks good to me

2022-07-25 16:23 UTC, timothycoleman approved these changes

2022-07-25 16:50 UTC, thefringeninja approved these changes

2022-07-26 17:10 UTC, jageall approved these changes

2022-07-26 17:10 UTC, merged