Update docs about deleting persistent subscriptions to $all over HTTP
EventStore/EventStore pull request #3593
Opened 2022-09-16 10:26 UTC by 321zer0

Changed: Deleting persistent subscriptions to $all over HTTP is not supported

2022-09-20 08:54 UTC, hayley-jean requested changes
The `Update` and `Create` operations also don't support persistent subscriptions to $all. So either we need a similar warning on each operation, or one at the top of the document that says that $all persistent subscriptions aren't supported over the HTTP API, and you should use gRPC instead.

I also think these should be in a warning block to make them more visible, like the TCP warning [here](https://developers.eventstore.com/server/v21.10/#tcp-protocol). You can do this by putting the text in a `::: warning` block like [this](https://github.com/EventStore/EventStore/blob/4e56eacb954814d9bb47b0ac9616d084688e6848/docs/README.md#tcp-protocol)

2022-09-21 08:43 UTC, 321zer0 commented
@hayley-jean Thanks for the review. I've added warning blocks and also instructions for the `update` and create `operations` as well

2022-09-21 08:59 UTC, Lougarou approved these changes

2022-09-21 09:05 UTC, hayley-jean approved these changes

2022-09-21 09:05 UTC, merged