Do not allow anonymous user to access some endpoints and streams in EventStoreDB
EventStore/EventStore pull request #3787
Opened 2023-03-15 21:07 UTC by dhingrak

Added: Restrict EventStoreDB access for an anonymous user
 
 Fixes #https://github.com/EventStore/home/issues/899
 
 This PR prevents the anonymous access to some endpoint and streams in EventStoreDB. We are also adding an option "AllowAnonymousAccess" to revert the authorization policy to the previous behaviour. 
 

Format | Syntax

Command line              | --allow-anonymous-access
YAML                             | AllowAnonymousAccess
Environment variable    | ALLOW_ANONYMOUS_ACCESS

Default: false

Note: Currently the allowAnonymousAccess value sets to true for unit tests.

2023-03-16 10:16 UTC, alexeyzimarev commented
Does it make sense to protect the `ping` endpoint?

2023-03-16 13:08 UTC, dhingrak commented
> Does it make sense to protect the `ping` endpoint?

I don't think there is any need to protect `ping` endpoint. Currently, I have locked down most of the endpoints until Hayley has a discussion with Tim and you regarding which endpoints will remain available to anonymous requests.

2023-03-27 15:59 UTC, hayley-jean commented
I think we should split this into two options:

| Name | Description | Default |
|--------|--------------|---------|
| AllowAnonymousEndpointAccess | Allows anonymous access to the gossip and stats endpoints | true |
| AllowAnonymousStreamAccess | Allows anonymous reads and writes to streams | ??? |

`Ping` should always allow anonymous access

The reason for this being that changing anonymous endpoint access will break a lot of deployments and monitoring configurations. It's quite possible that someone would want to keep anonymous access on endpoints enabled, but still want to lock down anonymous reads/writes to streams.

I'm still unsure about what the default for anonymous stream access should be. On the one hand, the fact that anonymous stream access is enabled by default is surprising to a lot of users, on the other, changing this default is a breaking change.

I would lean towards setting it to `true` by default, with the intentions of changing it to `false` with the release after next (and advertising this change appropriately before then)

2023-03-28 11:55 UTC, tambeau commented
Concur with Hayley on setting AllowAnonymousStreamAccess to True.

2023-03-29 14:54 UTC, timothycoleman commented on docs/security.md
> +For this to work, you can use the `AllowAnonymousEndpointAccess` option:
lets consider the wording here

2023-03-29 15:06 UTC, timothycoleman commented
we should probably record in the description here some justification for the anonymously accessible endpoints (ping, gossip read etc) in case we wonder why we decided this way later. are we sure about gossip?

2023-03-29 16:10 UTC, timothycoleman commented on src/EventStore.Core/Authorization/LegacyStreamPermissionAssertion.cs
> +					if (claim.Type == ClaimTypes.Anonymous) {
is it a bit odd to be checking for the existence of an anonymous claim rather than the absense of some other claim indicating that aren't anonymous

2023-03-30 08:19 UTC, timothycoleman requested changes
looks good, questions and sugguestions inline ^

2023-04-04 10:39 UTC, timothycoleman commented on src/EventStore.Core/Authorization/LegacyStreamPermissionAssertion.cs
> +					Log.Warning(
im not sure we need the warning and stopwatch in here, the ~same message will be logged in the PolicyAuthorizationProvider i think?

2023-04-04 11:59 UTC, timothycoleman commented on src/EventStore.Core/Authorization/LegacyStreamPermissionAssertion.cs
> +					Log.Warning(
actually scratch that, i dont think we should be changing this class at all, i'll push what i mean

2023-04-14 11:00 UTC, hayley-jean requested changes

2023-04-14 11:00 UTC, hayley-jean commented on src/EventStore.Core/Authorization/LegacyAuthorizationProviderFactory.cs
> +			policy.AllowAnonymous(Operations.Node.Gossip.Read);
`Operations.Node.Gossip.ClientRead` should be used for gossip requests from external clients, and `Operations.Node.Gossip.Read` should be used for node-to-node gossip.

As such, I think only `Gossip.ClientRead` should allow anonymous access. And perhaps the `Gossip.Read` operation should be further locked down to requiring system access?

That being said, the HTTP GossipController is registering `/gossip` as a `Gossip.Read` operation. This should really be changed to `Gossip.ClientRead` ([see here](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/Transport/Http/Controllers/GossipController.cs#L37))

2023-04-17 13:44 UTC, hayley-jean commented on src/EventStore.Core/Authorization/LegacyAuthorizationProviderFactory.cs
> +			policy.AllowAnonymous(Operations.Node.Gossip.Read);
In summary, changes needed:
- `Gossip.ClientRead` should use the `allow-anonymous-endpoints` option
- `Gossip.Read` should require a system user
- `/gossip` in the HTTP gossipController should be changed to use `Gossip.ClientRead`

2023-04-19 12:57 UTC, timothycoleman commented on src/EventStore.Core/Authorization/LegacyAuthorizationProviderFactory.cs
> +			policy.AllowAnonymous(Operations.Node.Gossip.ClientRead);
and this is the one that should be configurable

2023-04-20 08:04 UTC, timothycoleman commented
Looks good, I think the tests need updating following the latest change, and the original description in the ticket ^

Actually for the 'added' line perhaps adjust slightly

`Added: Option to restrict EventStoreDB access for an anonymous user`

2023-04-21 08:28 UTC, timothycoleman approved these changes
good work :+1:

2023-04-21 10:01 UTC, hayley-jean approved these changes
Looks good, thank you 👍

2023-04-21 10:01 UTC, merged