Combine InaugurationStatusTracker into NodeStatusTracker
EventStore/EventStore pull request #3802
Opened 2023-03-29 14:25 UTC by timothycoleman

Since ultimately the inauguration status is a substatus of the PreLeader nodestatus

![image](https://user-images.githubusercontent.com/2587665/228570203-13744d24-4e41-4d7d-8519-aaa657b21907.png)

2023-03-29 14:27 UTC, YoEight approved these changes

2023-03-31 09:46 UTC, hayley-jean requested changes
The build is failing because there's still a reference to `InaugurationStatusTracker` in the `MetricsBootstrapper` [here](https://github.com/EventStore/EventStore/pull/3802/files#diff-343bdc215ab8a1cba5fd26e1e548fb6fc75c0b60827c127c642890185cc84f6fR16)

2023-03-31 13:54 UTC, timothycoleman commented
well woops, not sure how i managed that. fixed

2023-04-04 13:34 UTC, hayley-jean approved these changes

2023-04-05 12:35 UTC, YoEight approved these changes

2023-04-05 12:35 UTC, merged