Verify if the TCP client has any persistent subscription before logging the persistent subscription dropped message on the server.
EventStore/EventStore pull request #3824
Opened 2023-04-24 22:05 UTC by dhingrak

Fixed: #https://github.com/EventStore/home/issues/65

The goal of this PR is to verify whether the dropped TCP connection has any persistent subscription before logging the persistent subscription dropped message in the server logs.

2023-04-26 10:54 UTC, timothycoleman commented on src/EventStore.Core/Services/PersistentSubscription/PersistentSubscriptionClientCollection.cs
> +				unconfirmedEvents = new OutstandingMessage[0];
we can probably use Array.Empty here and avoid the allocation

2023-04-26 10:56 UTC, timothycoleman commented on src/EventStore.Core/Services/PersistentSubscription/PersistentSubscriptionClientCollection.cs
> +
minor but ideally best not to add these tabs

2023-04-26 10:56 UTC, timothycoleman commented on src/EventStore.Core/Services/PersistentSubscription/PersistentSubscriptionService.cs
>  			//TODO CC make a map for this
i think we can remove this comment now

2023-04-26 10:58 UTC, timothycoleman commented on src/EventStore.Core/Services/PersistentSubscription/PersistentSubscriptionService.cs
> +					message.Connection.RemoteEndPoint);
minor, adjust the formatting

2023-04-26 11:00 UTC, timothycoleman commented on src/EventStore.Core/Services/PersistentSubscription/PersistentSubscription.cs
> +					if (ActionTakenForRetriedMessage(m)) // currently we are not iterating over remaining messages if the condition return true. It should continue with the other messages, might be a bug
we can ponder this but i dont think we need a comment in the code for it

2023-04-26 11:00 UTC, timothycoleman requested changes
looks great :+1:, minor comments inline

2023-04-28 08:08 UTC, timothycoleman approved these changes
:+1: thanks!

2023-05-01 10:05 UTC, hayley-jean approved these changes

2023-05-01 10:05 UTC, merged