Log error message when the SSL handshakes fail [DB-32]
EventStore/EventStore pull request #3832
Opened 2023-05-03 17:08 UTC by dhingrak

Fixed: Log more readable error message in the server logs when the SSL handshakes fail.

Fixes #3765 

The goal of this PR to add more readable error messages rather than dumping the error status when the SSL handshakes fail.

2023-05-05 09:59 UTC, hayley-jean requested changes

2023-05-05 09:59 UTC, hayley-jean commented on src/EventStore.Core/ClusterVNode.cs
> +			var chainStatus = CertificateUtils.BuildChain(certificate, intermediates, trustedRootCertsSelector(), out _);
The `chainStatusInformation` returned from this call to `BuildChain` should also be captured and logged to give more detailed information about why other nodes' certificates are invalid

2023-05-16 11:20 UTC, hayley-jean approved these changes

2023-05-16 12:39 UTC, timothycoleman approved these changes

2023-05-16 12:40 UTC, merged