Add a check to verify is something is blocking the data transfer between nodes
EventStore/EventStore pull request #3839
Opened 2023-05-15 16:24 UTC by dhingrak

Fixed: Detect data transfer blocking between nodes.

Fixes #3766 

Currently we are logging the message as connection lost even the node cannot reach to another node due to some reasons. For example, a firewall configuration blocks the necessary port. The goal of this PR is to log a warning to differentiate whether the connection is lost or the connection is blocked for some reasons.

2023-05-22 12:26 UTC, hayley-jean approved these changes
The changes look good

As a note, this should also log the warning for external client connections that close without sending/receiving data

2023-05-22 13:32 UTC, hayley-jean requested changes
After discussing during standup, it would be better to only log this warning if the connection was opened by the server (as opposed to having been opened by another node or client). This would prevent the warning from being logged for connections that were opened by an external client and then the client immediately dropping it

2023-05-26 11:20 UTC, timothycoleman approved these changes

2023-05-26 12:18 UTC, hayley-jean approved these changes

2023-05-26 12:19 UTC, merged