Add steps for rolling certificate update
EventStore/EventStore pull request #3940
Opened 2023-08-29 15:59 UTC by dhingrak

Added:  Add steps to update certificates

Fixes https://linear.app/eventstore/issue/DB-190/rolling-certificate-update-documentation

2023-09-05 12:12 UTC, hayley-jean commented on docs/operations.md
> +**Note:** The connection between nodes in EventStoreDB reset every 10 minutes so the new configuration won’t take immediate effect. The user has this timeframe to update the certificates on all the n
```suggestion
The connection between nodes in EventStoreDB reset every 10 minutes so the new configuration won’t take immediate effect. The user has this timeframe to update the certificates on all the nodes. It is advisable to monitor the cluster after this timeframe to make sure everything is working fine.
```

2023-09-11 13:12 UTC, hayley-jean requested changes
Thanks, just some small further changes

2023-09-11 13:12 UTC, hayley-jean commented on docs/operations.md
> +The next step is to replace the newly generated certificates in a subfolder and update the symlink to point it to the new certificates.
```suggestion
The next step is to replace the outdated certificates with the newly generated certificates.

 If you are using symlinks then you can update the symlink to point it to the new certificates.
```

2023-09-11 13:12 UTC, hayley-jean commented on docs/operations.md
> +[108277,30,14:46:07.453,INF] Reloading the node's configuration since a request has been received on /admin/reloadconfig.
The code block should just wrap the logs, so start below the "Once the configuration...." text

2023-09-11 13:12 UTC, hayley-jean commented on docs/operations.md
> +[108277,30,14:49:47.481,INF] Reloading the node's configuration since a request has been received on /admin/reloadconfig.
Same with above, the code block should wrap the logs, so start below the "For example..." text

2023-09-11 13:37 UTC, hayley-jean commented
@EventStore/documentation this is ready for review

2023-09-11 15:51 UTC, dhingrak commented
update formatting as requested.

2023-09-12 12:57 UTC, hayley-jean commented on docs/operations.md
> +### Step 3: Reload the configuration
Just one other thing to add here - we can also trigger a certificate reload by sending a SIGHUP signal to the EventStore process (on Linux only). We should mention this here too.

2023-09-20 17:26 UTC, cdevarenne approved these changes
Minor issues in the wording and format will be addressed in a different PR.

2023-09-20 17:37 UTC, rsowald approved these changes

2023-09-21 11:23 UTC, hayley-jean approved these changes

2023-09-21 11:23 UTC, merged