Improve the error message when subscribing from an invalid position
EventStore/EventStore pull request #3963
Opened 2023-09-21 15:30 UTC by lakshdeepsingheventstore

Fixed : https://github.com/EventStore/EventStore/issues/3195
Improves the error message on the client side when a catch subscription is created from an invalid position. When the above mentioned exception was thrown, the error message on the client side was unclear stating "An exception was thrown by the handler", without specifying the actual error message, thus making it difficult to diagnose what the actual issue was.This PR improves the error message when the above issue is encountered.

2023-10-05 16:27 UTC, hayley-jean requested changes
This error handling should also be added to the FilteredAllSubscription

2023-10-05 18:42 UTC, lakshdeepsingheventstore commented on src/EventStore.Core/Services/Transport/Grpc/RpcExceptions.cs
> +			new(new Status(StatusCode.Unknown, $"Trying to read from an invalid position."));
Done

2023-10-05 18:42 UTC, lakshdeepsingheventstore commented on src/EventStore.Core/Services/Transport/Grpc/Enumerators.AllSubscription.cs
> +					} catch (Exception ex) {
Done

2023-10-30 13:16 UTC, hayley-jean approved these changes

2023-10-31 14:17 UTC, timothycoleman commented on src/EventStore.Core/Services/Transport/Grpc/Enumerators.AllSubscription.cs
> +					IndexReadAllResult indexResult = new IndexReadAllResult();
the declaration of this variable can be left inside the try i think?

2023-11-07 10:50 UTC, timothycoleman approved these changes

2023-11-13 10:08 UTC, hayley-jean approved these changes

2023-11-13 10:08 UTC, merged