Add documentation for certificate improvements [DB-451]
EventStore/EventStore pull request #4000
Opened 2023-10-17 12:18 UTC by shaan1337

Added: documentation for certificate improvements

2023-10-18 10:42 UTC, timothycoleman submitted a review, later dismissed

2023-10-18 17:37 UTC, cdevarenne requested changes

2023-10-18 17:37 UTC, cdevarenne commented on docs/operations.md
> +As of version 23.10.0, it is possible to do a rolling update with new certificates having a Common Name (CN) that's different to the original certificates. If `CertificateReservedNodeCommonName` was
```suggestion
As of version 23.10.0, it is possible to do a rolling update with new certificates having a Common Name (CN) that's different from the original certificates. If `CertificateReservedNodeCommonName` was set in your configuration, any changes to its value will be taken into consideration during a config reload.
```

2023-10-23 13:34 UTC, shaan1337 commented on docs/operations.md
> +As of version 23.10.0, it is possible to do a rolling update with new certificates having a Common Name (CN) that's different to the original certificates. If `CertificateReservedNodeCommonName` was
fixed, thanks!

2023-10-23 14:08 UTC, timothycoleman approved these changes

2023-10-23 14:08 UTC, cdevarenne approved these changes

2023-10-23 14:09 UTC, merged