Add an upgrade guide for EventStoreDB 23.10.0
EventStore/EventStore pull request #4019
Opened 2023-10-27 13:10 UTC by hayley-jean

2023-10-27 13:17 UTC, rmalik-es approved these changes

2023-10-27 17:13 UTC, cdevarenne requested changes

2023-10-27 17:13 UTC, cdevarenne commented on docs/upgrade-guide.md
> +If you want to revert back to the old behaviour, you can enable the `AllowAnonymousStreamAccess` and `AllowAnonymousEndpointAccess` options in EventStoreDB.
```suggestion
If you want to revert back to the old behavior, you can enable the `AllowAnonymousStreamAccess` and `AllowAnonymousEndpointAccess` options in EventStoreDB.
```

2023-10-27 17:13 UTC, cdevarenne commented on docs/upgrade-guide.md
> +Requests to the HTTP API must be authenticated by default
```suggestion
Requests to the HTTP API must be authenticated by default.
```

2023-10-30 09:50 UTC, ylorph approved these changes

2023-10-30 13:41 UTC, cdevarenne approved these changes

2023-10-30 14:24 UTC, timothycoleman approved these changes

2023-10-30 14:45 UTC, merged