[DOC-66] copy edit pass on Operations
EventStore/EventStore pull request #4024
Opened 2023-10-30 21:55 UTC by rsowald

2023-10-30 23:09 UTC, cdevarenne requested changes
In genral, because it's a linux command `cron` is not capitalized.

2023-10-30 23:09 UTC, cdevarenne commented on docs/operations.md
>  ## Scavenging HTTP options
```suggestion
## Starting a scavenge
```

2023-10-30 23:09 UTC, cdevarenne commented on docs/operations.md
>  If this procedure is impractical in your use case, then you can use the redaction tool (the "redactor") to blank out the data of specific events.
```suggestion
If this procedure is impractical for your use case, then you can use the redaction tool (the "redactor") to blank out the data of specific events.
```

2023-10-31 00:08 UTC, rsowald commented on docs/operations.md
> +You can set up a scheduled task, for example using [Cron](https://cron.com/) or [Windows Task Scheduler](https://learn.microsoft.com/en-us/windows/win32/taskschd/task-scheduler-start-page), to trigge
🤔 isn't Cron a proper noun? Is this not referring to Cron Calendar?

2023-10-31 00:45 UTC, cdevarenne requested changes

2023-10-31 00:45 UTC, cdevarenne commented on docs/operations.md
> +You can set up a scheduled task, for example using [Cron](https://cron.com/) or [Windows Task Scheduler](https://learn.microsoft.com/en-us/windows/win32/taskschd/task-scheduler-start-page), to trigge
```suggestion
You can set up a scheduled task, for example using cron on Linux or [Windows Task Scheduler](https://learn.microsoft.com/en-us/windows/win32/taskschd/task-scheduler-start-page), to trigger a scavenge as often as you need.
```

2023-10-31 16:34 UTC, cdevarenne submitted a review, later dismissed

2023-11-01 18:38 UTC, cdevarenne approved these changes

2023-11-02 17:44 UTC, rmalik-es approved these changes

2023-11-02 22:39 UTC, merged