[DOC-7] Fix links from security/configuration to installation doc
EventStore/EventStore pull request #4034
Opened 2023-11-01 20:09 UTC by rsowald

The installation doc is not in an `installation/` directory in this version. Fixing links to follow the correct path.

2023-11-01 20:29 UTC, cdevarenne requested changes

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
>  We realise that many users want to try out the latest version with their existing applications, and also run a previous version of EventStoreDB without any security in their internal networks.
```suggestion
We realize that many users want to try out the latest version with their existing applications, and also run a previous version of EventStoreDB without any security in their internal networks.
```

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
> +SSL certificates can be created with a common name (CN), which is an arbitrary string. Usually is contains the DNS name for which the certificate is issued. When cluster nodes connect to each other,
```suggestion
SSL certificates can be created with a common name (CN), which is an arbitrary string. Usually it contains the DNS name for which the certificate is issued. When cluster nodes connect to each other, they need to ensure that they indeed talk to another node and not something that pretends to be a node. Therefore, EventStoreDB expects the connecting party to have a certificate with a pre-defined CN `eventstoredb-node`.
```

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
> +As the first step CA certificate needs to be generated. It'll need to be trusted for each of the nodes and client environment.
```suggestion
As the first step, a CA certificate needs to be generated. It'll need to be trusted for each of the nodes and client environment.
```

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
> +- `ca.key` - private key file that should be used only in the nodes configuration (**Do not copy it to client environment**).
```suggestion
- `ca.key` - private key file that should be used only in the nodes configuration (**Do not copy it to client environments**).
```

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
>  You can customise generated cert by providing following params:
```suggestion
You can customize the generated cert by providing the following parameters:
```

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
> +- `node.key` - the private key file that should be used only in the node's configuration (**Do not copy it to client environment**).
```suggestion
- `node.key` - the private key file that should be used only in the node's configuration (**Do not copy it to client environments**).
```

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
>  You can customise generated cert by providing following params:
```suggestion
You can customize the generated cert by providing the following parameters:
```

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
> +1. Copy auto-generated CA file to dir `/usr/local/share/ca-certificates/`, e.g. using command:
```suggestion
1. Copy the auto-generated CA file to `/usr/local/share/ca-certificates/`, e.g. using command:
```

2023-11-01 20:29 UTC, cdevarenne commented on docs/security/configuration.md
>  1. You can manually import it to the local CA cert store through `Certificates Local Machine Management Console`. To do that select **Run** from the **Start** menu, and then enter `certmgr.msc`. Then
```suggestion
1. You can manually import it to the local CA cert store through `Certificates Local Machine Management Console`. To do that select **Run** from the **Start** menu, and then enter `certmgr.msc`. Then import the certificate to `Trusted Root Certification`.
```

2023-11-01 23:04 UTC, cdevarenne approved these changes

2023-11-15 08:13 UTC, timothycoleman approved these changes

2023-11-15 19:10 UTC, merged