DOC-77 Update README References to replace Beta
EventStore/EventStore pull request #4041
Opened 2023-11-03 14:26 UTC by rmalik-es

Removed "beta" from mentioned python client

2023-11-03 15:33 UTC, cdevarenne approved these changes

2023-11-03 16:23 UTC, rsowald submitted a review, later dismissed

2023-11-16 00:36 UTC, cdevarenne requested changes

2023-11-16 00:36 UTC, cdevarenne commented on README.md
> +- Python: [pyeventsourcing/esdbclient](https://github.com/pyeventsourcing/esdbclient)
```suggestion
- Python: [pyeventsourcing/esdbclient](https://pypi.org/project/esdbclient/) 
```

2023-11-16 00:38 UTC, cdevarenne approved these changes

2023-11-16 02:45 UTC, rsowald approved these changes

2023-11-16 05:40 UTC, merged