Update changelog for 24.2.0
EventStore/EventStore pull request #4167
Opened 2024-02-26 17:22 UTC by hayley-jean

2024-02-27 08:04 UTC, timothycoleman approved these changes

2024-02-27 08:08 UTC, timothycoleman requested changes
just the jint thing

2024-02-28 11:58 UTC, timothycoleman submitted a review, later dismissed

2024-02-28 12:50 UTC, shaan1337 commented on CHANGELOG.md
>  - Unncessary code [EventStore#4087](https://github.com/EventStore/EventStore/pull/4087)
```suggestion
- Unnecessary code [EventStore#4087](https://github.com/EventStore/EventStore/pull/4087)
```

2024-02-28 12:57 UTC, timothycoleman approved these changes

2024-02-28 12:58 UTC, shaan1337 approved these changes

2024-02-28 12:58 UTC, merged