Always replicate the chunk header [DB-719]
EventStore/EventStore pull request #4211
Opened 2024-03-21 07:08 UTC by shaan1337

Changed: Always replicate the chunk header

This PR causes followers to always replicate the chunk header from the leader. It is a pre-requisite for the encryption at rest plugin. Prior to this PR, the chunk header was replicated only for scavenged chunks.

This change has an additional benefit: it's easy for sysadmins to compare files on a leader and a follower by using standard tools like `md5sum`, `sha1sum`, etc. without needing to exclude the first 128 bytes from the comparison (as previously, the chunk ID were different on the leader and followers)

2024-03-29 05:59 UTC, shaan1337 commented
Please don't merge yet, as some additional tests are probably needed.

2024-03-29 06:00 UTC, shaan1337 commented on src/EventStore.Core/Services/Replication/LeaderReplicationService.cs
> +							isCompletedChunk: false));
To verify: is this always `false` ? as in some cases, this block may be entered when the chunk is scavenged

2024-05-23 06:01 UTC, shaan1337 commented on src/EventStore.Core/Services/Replication/LeaderReplicationService.cs
> +							isCompletedChunk: false));
fixed in: https://github.com/EventStore/EventStore/pull/4265

this PR needs to be rebased once the above PR is merged.

2024-05-31 16:17 UTC, hayley-jean requested changes
The replicated chunks seem to lose the version in their filenames when they are replicated.
e.g. `chunk-000001.000001` on the leader is replicated as `chunk-000001.000000` on the follower.

2024-06-04 10:07 UTC, shaan1337 commented on src/EventStore.Core/Cluster/ReplicationPartials.cs
> +			// sending an empty byte array will cause an error (BadRequest) on the follower without halting replication
@hayley-jean nice catch! i've just pushed a fix for it, the previous code wasn't populating the old chunk header field at all for scavenged chunks, thereby causing this exception (i haven't tested it yet to confirm if it's fixed though)

2024-06-04 10:18 UTC, shaan1337 commented
> The replicated chunks seem to lose the version in their filenames when they are replicated. e.g. `chunk-000001.000001` on the leader is replicated as `chunk-000001.000000` on the follower.

nice find! I believe that this bug already existed prior to this PR due to this call in SwitchChunk:
https://github.com/EventStore/EventStore/blob/aa6c0a2381fc590a8cd76ca7942d21b72a86363c/src/EventStore.Core/TransactionLog/Chunks/TFChunkManager.cs#L191

it could easily be fixed by specifying a minimum value of 1 for the chunk version (although the versions wouldn't necessarily match with the leader)

it's quite important to fix it as some places in the code assume that a chunk with version 0 hasn't been scavenged:
e.g on startup, it assumes that the next chunk number is just incremented by one:
https://github.com/EventStore/EventStore/blob/aa6c0a2381fc590a8cd76ca7942d21b72a86363c/src/EventStore.Core/TransactionLog/Chunks/TFChunkEnumerator.cs#L64

2024-06-04 11:28 UTC, shaan1337 commented
> > The replicated chunks seem to lose the version in their filenames when they are replicated. e.g. `chunk-000001.000001` on the leader is replicated as `chunk-000001.000000` on the follower.
> 
> nice find! I believe that this bug already existed prior to this PR due to this call in SwitchChunk:
> 
> https://github.com/EventStore/EventStore/blob/aa6c0a2381fc590a8cd76ca7942d21b72a86363c/src/EventStore.Core/TransactionLog/Chunks/TFChunkManager.cs#L191
> 
> it could easily be fixed by specifying a minimum value of 1 for the chunk version (although the versions wouldn't necessarily match with the leader)
> 
> it's quite important to fix it as some places in the code assume that a chunk with version 0 hasn't been scavenged: e.g on startup, it assumes that the next chunk number is just incremented by one:
> 
> https://github.com/EventStore/EventStore/blob/aa6c0a2381fc590a8cd76ca7942d21b72a86363c/src/EventStore.Core/TransactionLog/Chunks/TFChunkEnumerator.cs#L64

sorry, my bad, it is actually a bug introduced in this PR, i'll push a fix for it

2024-06-04 11:53 UTC, shaan1337 commented on src/EventStore.Core/Cluster/ReplicationPartials.cs
> +			// sending an empty byte array will cause an error (BadRequest) on the follower without halting replication
confirming that the fix works

2024-06-05 14:50 UTC, timothycoleman approved these changes
Nice looks good.
I've tested backwards and forwards compatibility for replication

2024-06-05 14:51 UTC, merged