Add how to resign or change leader in eventstore in the api document.
EventStore/EventStore pull request #4479
Opened 2024-10-03 17:35 UTC by CindyLoMinChung

Add how to resign or change a leader under API documentation.

2024-10-03 17:46 UTC, coloradomorrissey approved these changes

2024-10-03 17:55 UTC, timothycoleman requested changes
actually just hold on this one for a mo, i think we made it so you no longer have to reduce the priority - @hayley-jean ?

2024-10-04 06:08 UTC, timothycoleman commented
Ah yes it was here https://github.com/EventStore/EventStore/pull/4371 which affects only 24.10, so we can adjust that in the cherry pick to master

2024-10-04 06:13 UTC, timothycoleman approved these changes

2024-10-04 06:13 UTC, merged