Fix Shutdown service.
EventStore/EventStore pull request #4563
Opened 2024-10-23 02:46 UTC by YoEight

Fixed: Fix Shutdown service.

2024-10-23 15:36 UTC, timothycoleman approved these changes

2024-10-23 16:02 UTC, RagingKore requested changes

2024-10-23 16:02 UTC, RagingKore commented on src/EventStore.Core/Services/ShutdownService.cs
> +			return;
We should log DEBUG on this exit too

2024-10-23 16:16 UTC, timothycoleman commented on src/EventStore.Core/Services/ShutdownService.cs
> +			Log.Warning("Component {ComponentName} registered for graceful shutdown while the server is shutting down",
I’m not sure I follow this

2024-10-23 17:21 UTC, RagingKore commented on src/EventStore.Core/Services/ShutdownService.cs
> +			Log.Warning("Component {ComponentName} registered for graceful shutdown while the server is shutting down",
The component never got registered. The log message should reflect that.

2024-10-24 06:22 UTC, timothycoleman approved these changes

2024-10-24 08:22 UTC, RagingKore approved these changes
LGTM

2024-10-24 08:38 UTC, merged